server {
    listen 80;

    server_name {{ DOMAIN }};

    root {{ ROOT }};
    index index.html;

    access_log /var/log/nginx/{{ DOMAIN }}.access.log;
    error_log  /var/log/nginx/{{ DOMAIN }}.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}